# Generated by Django 2.2.5 on 2020-03-03 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrape',
            old_name='city',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='scrape',
            old_name='organic',
            new_name='sponsored',
        ),
        migrations.AddField(
            model_name='scrape',
            name='lovation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrape',
            name='salary',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
