# Generated by Django 2.2.5 on 2020-03-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200303_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrape',
            old_name='lovation',
            new_name='location',
        ),
    ]
