# Generated by Django 2.2.5 on 2020-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200303_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
