# Generated by Django 2.2.5 on 2020-03-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200303_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
