# Generated by Django 2.2.8 on 2020-01-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drop_Cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
