# Generated by Django 2.2.8 on 2020-01-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drop_Cv', '0002_auto_20200128_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Image',
            new_name='File',
        ),
    ]
