# Generated by Django 2.2.8 on 2020-02-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drop_Cv', '0003_auto_20200128_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='File',
            field=models.FileField(upload_to='files/'),
        ),
    ]
