# Generated by Django 2.2.8 on 2020-02-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drop_Cv', '0004_auto_20200202_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='File',
        ),
    ]
