# Generated by Django 2.2.8 on 2020-02-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drop_Cv', '0005_remove_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='FullName',
            field=models.CharField(max_length=100),
        ),
    ]
