# Generated by Django 2.2.8 on 2020-02-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drop_Cv', '0007_auto_20200203_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
