# Generated by Django 2.2.8 on 2020-02-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drop_Cv', '0009_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
